### PR TITLE
Prepare version 2.0.0

### PR DESCRIPTION
**Pull request by cyrille-leclerc**
Prepare version 2.0.0 based on cloudbees/java-build-tools:2.0.0 which is a bump of Ubuntu from 15.04 to 16.04 + bump of selenium-standalone-server from 2.x to 3.x.

### CODE REVIEW

**Comment by cyrille-leclerc** [comment]
@reviewbybees /cc @ndeloof @ydubreuil @schottsfired @dduportal

**Comment by ydubreuil** [comment]
Updating remoting JAR could be nice maybe? Lots of fixes are available in 3.X line IIRC

Apart from that SGTM

**Comment by cyrille-leclerc** [comment]
Thanks @ydubreuil. I don't know how I didn't catch that 3.x was out when I bumped remoting. It's fixed.

**Comment by dduportal** [comment]
🐝  , LGTM or 🍺  (whatever you prefer :) )

**Comment by schottsfired** [comment]
👍

**Pull request merged**
